services:
  - xvfb

language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install graphviz

install:
  - pip install -U pip
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov