services:
  - xvfb

language: python

python:
  - "3.6"

addons:
  artifacts:
    paths:
      - result_images.tar.bz2

before_install:
  - sudo apt-get install graphviz

install:
  - pip install -U pip
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov

after_failure: |
  tar cjf result_images.tar.bz2 result_images